"""adiciona data_pagamento em dativos_itens

Revision ID: 1675bc314225
Revises: 8af736b9f0d5
Create Date: 2026-03-13 11:09:55.357333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1675bc314225'
down_revision = '8af736b9f0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dativos_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dativos_itens', schema=None) as batch_op:
        batch_op.drop_column('data_pagamento')

    # ### end Alembic commands ###
