"""adiciona estrutura base de dativos

Revision ID: 8af736b9f0d5
Revises: aa00fffa0306
Create Date: 2026-03-13 07:23:32.528905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af736b9f0d5'
down_revision = 'aa00fffa0306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dativos_ci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercicio', sa.String(length=7), nullable=False),
    sa.Column('processo_edoc', sa.String(length=50), nullable=False),
    sa.Column('data_ci', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dativos_ci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dativos_ci_exercicio'), ['exercicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_dativos_ci_processo_edoc'), ['processo_edoc'], unique=True)

    op.create_table('dativos_lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dativo_ci_id', sa.Integer(), nullable=False),
    sa.Column('tipo_lote', sa.String(length=20), nullable=False),
    sa.Column('quantidade_itens', sa.Integer(), nullable=False),
    sa.Column('valor_total_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_total_irrf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_total_liquido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('nota_empenho', sa.String(length=50), nullable=True),
    sa.Column('ordem_bancaria', sa.String(length=50), nullable=True),
    sa.Column('situacao_rpv_id', sa.Integer(), nullable=False),
    sa.Column('situacao_imposto_id', sa.Integer(), nullable=False),
    sa.Column('resumo_operacional', sa.String(length=500), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['dativo_ci_id'], ['dativos_ci.id'], ),
    sa.ForeignKeyConstraint(['situacao_imposto_id'], ['situacoes_imposto.id'], ),
    sa.ForeignKeyConstraint(['situacao_rpv_id'], ['situacoes_empenho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dativos_lotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dativos_lotes_dativo_ci_id'), ['dativo_ci_id'], unique=False)

    op.create_table('dativos_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dativo_ci_id', sa.Integer(), nullable=False),
    sa.Column('dativo_lote_id', sa.Integer(), nullable=True),
    sa.Column('grupo', sa.String(length=20), nullable=False),
    sa.Column('nome_beneficiario', sa.String(length=200), nullable=False),
    sa.Column('nome_beneficiario_normalizado', sa.String(length=200), nullable=False),
    sa.Column('cpf_original', sa.String(length=20), nullable=False),
    sa.Column('cpf_normalizado', sa.String(length=20), nullable=False),
    sa.Column('numero_processo', sa.String(length=50), nullable=False),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_irrf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('nota_empenho', sa.String(length=50), nullable=True),
    sa.Column('ordem_bancaria', sa.String(length=50), nullable=True),
    sa.Column('ob_imposto', sa.String(length=50), nullable=True),
    sa.Column('situacao_rpv_id', sa.Integer(), nullable=False),
    sa.Column('situacao_imposto_id', sa.Integer(), nullable=False),
    sa.Column('resumo_operacional', sa.String(length=500), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['dativo_ci_id'], ['dativos_ci.id'], ),
    sa.ForeignKeyConstraint(['dativo_lote_id'], ['dativos_lotes.id'], ),
    sa.ForeignKeyConstraint(['situacao_imposto_id'], ['situacoes_imposto.id'], ),
    sa.ForeignKeyConstraint(['situacao_rpv_id'], ['situacoes_empenho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dativos_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dativos_itens_cpf_normalizado'), ['cpf_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_dativos_itens_dativo_ci_id'), ['dativo_ci_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dativos_itens_dativo_lote_id'), ['dativo_lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dativos_itens_grupo'), ['grupo'], unique=False)
        batch_op.create_index(batch_op.f('ix_dativos_itens_nome_beneficiario_normalizado'), ['nome_beneficiario_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_dativos_itens_numero_processo'), ['numero_processo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dativos_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dativos_itens_numero_processo'))
        batch_op.drop_index(batch_op.f('ix_dativos_itens_nome_beneficiario_normalizado'))
        batch_op.drop_index(batch_op.f('ix_dativos_itens_grupo'))
        batch_op.drop_index(batch_op.f('ix_dativos_itens_dativo_lote_id'))
        batch_op.drop_index(batch_op.f('ix_dativos_itens_dativo_ci_id'))
        batch_op.drop_index(batch_op.f('ix_dativos_itens_cpf_normalizado'))

    op.drop_table('dativos_itens')
    with op.batch_alter_table('dativos_lotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dativos_lotes_dativo_ci_id'))

    op.drop_table('dativos_lotes')
    with op.batch_alter_table('dativos_ci', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dativos_ci_processo_edoc'))
        batch_op.drop_index(batch_op.f('ix_dativos_ci_exercicio'))

    op.drop_table('dativos_ci')
    # ### end Alembic commands ###
