"""ajusta exercicio para mes e ano

Revision ID: aa00fffa0306
Revises: e650c7a8d5ad
Create Date: 2026-03-12 10:02:52.162562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa00fffa0306'
down_revision = 'e650c7a8d5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.alter_column('exercicio',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.alter_column('exercicio',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
