"""adiciona processos e registros_rpv

Revision ID: e650c7a8d5ad
Revises: f8acc8ed1412
Create Date: 2026-03-11 12:30:16.993551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e650c7a8d5ad'
down_revision = 'f8acc8ed1412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('processo_edoc', sa.String(length=50), nullable=False),
    sa.Column('numero_processo', sa.String(length=50), nullable=False),
    sa.Column('data_ci', sa.Date(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_exercicio'), ['exercicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_numero_processo'), ['numero_processo'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_processo_edoc'), ['processo_edoc'], unique=False)

    op.create_table('registros_rpv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('elaborador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_rpv_id', sa.Integer(), nullable=False),
    sa.Column('nome_beneficiario', sa.String(length=200), nullable=False),
    sa.Column('nome_beneficiario_normalizado', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('documento_original', sa.String(length=30), nullable=False),
    sa.Column('documento_normalizado', sa.String(length=20), nullable=False),
    sa.Column('documento_corrigido', sa.String(length=20), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_irrf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('possui_irrf', sa.Boolean(), nullable=False),
    sa.Column('imposto_texto', sa.String(length=30), nullable=True),
    sa.Column('nota_empenho', sa.String(length=50), nullable=True),
    sa.Column('situacao_empenho_id', sa.Integer(), nullable=False),
    sa.Column('situacao_imposto_id', sa.Integer(), nullable=False),
    sa.Column('ordem_bancaria', sa.String(length=50), nullable=True),
    sa.Column('reinf_status', sa.String(length=30), nullable=True),
    sa.Column('ob_imposto', sa.String(length=50), nullable=True),
    sa.Column('historico_auto', sa.String(length=500), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['elaborador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.ForeignKeyConstraint(['situacao_empenho_id'], ['situacoes_empenho.id'], ),
    sa.ForeignKeyConstraint(['situacao_imposto_id'], ['situacoes_imposto.id'], ),
    sa.ForeignKeyConstraint(['tipo_rpv_id'], ['tipos_rpv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_rpv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_rpv_documento_normalizado'), ['documento_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_rpv_nome_beneficiario_normalizado'), ['nome_beneficiario_normalizado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_rpv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_rpv_nome_beneficiario_normalizado'))
        batch_op.drop_index(batch_op.f('ix_registros_rpv_documento_normalizado'))

    op.drop_table('registros_rpv')
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_processo_edoc'))
        batch_op.drop_index(batch_op.f('ix_processos_numero_processo'))
        batch_op.drop_index(batch_op.f('ix_processos_exercicio'))

    op.drop_table('processos')
    # ### end Alembic commands ###
