"""adiciona data_pagamento em dativos_lotes

Revision ID: ef6d5efc735e
Revises: 1675bc314225
Create Date: 2026-03-18 10:27:14.242279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d5efc735e'
down_revision = '1675bc314225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dativos_lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_pagamento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dativos_lotes', schema=None) as batch_op:
        batch_op.drop_column('data_pagamento')

    # ### end Alembic commands ###
