"""criacao inicial das tabelas basicas

Revision ID: f8acc8ed1412
Revises: 
Create Date: 2026-03-11 12:15:39.588768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8acc8ed1412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situacoes_empenho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cor_badge', sa.String(length=20), nullable=True),
    sa.Column('ordem_fluxo', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('situacoes_empenho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_situacoes_empenho_nome'), ['nome'], unique=True)

    op.create_table('situacoes_imposto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cor_badge', sa.String(length=20), nullable=True),
    sa.Column('ordem_fluxo', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('situacoes_imposto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_situacoes_imposto_nome'), ['nome'], unique=True)

    op.create_table('tipos_rpv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipos_rpv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_rpv_nome'), ['nome'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_login'), ['login'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_login'))

    op.drop_table('usuarios')
    with op.batch_alter_table('tipos_rpv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_rpv_nome'))

    op.drop_table('tipos_rpv')
    with op.batch_alter_table('situacoes_imposto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_situacoes_imposto_nome'))

    op.drop_table('situacoes_imposto')
    with op.batch_alter_table('situacoes_empenho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_situacoes_empenho_nome'))

    op.drop_table('situacoes_empenho')
    # ### end Alembic commands ###
